apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: socket-service-backend
spec:
  healthCheck:
    timeoutSec: 5
    checkIntervalSec: 10
    type: HTTP
    requestPath: /test/hello
    port: 8080