apiVersion: v1
kind: Service
metadata:
  name: socket-service
  annotations:
    cloud.google.com/backend-config: '{"default": "socket-service-backend"}'
spec:
  selector:
    app: socket-app
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP